language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"

env:
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.2
  - DJANGO_VERSION=3.0
  - DJANGO_VERSION=3.1

before_install:
  - pip install pip --upgrade

install:
  - python setup.py install

before_script:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install -r test_web/requirements.txt
  - wget http://test.mosquitto.org/ssl/mosquitto.org.crt -O ./test_web/ca/mosquitto.org.crt

script:
  - python manage.py test
  - coverage run --source='.' manage.py test
  - coverage report -m --skip-covered
